name: zahran
description: Zahran Project
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  reusable:
    path: ../reusable
  fcm_config: ^3.0.7
  firebase_analytics: 8.1.2
#  firebase_crashlytics: 2.0.7
  geolocator: 7.2.0+1
  rxdart: 0.27.1
  http: 0.13.3
  google_maps_flutter: 2.0.6
  shimmer: 2.0.0
  connectivity: 3.0.6
  shared_preferences: 2.0.6
  flare_flutter: 3.0.1
  flutter_secure_storage: 4.2.0
  image_picker: 0.8.1+3
  date_format: 2.0.2
  expandable: 5.0.1
  # flutter_sound: 8.1.9
  url_launcher: ^6.0.9
  permission_handler: 8.1.2
  # stack_trace: 1.10.0
  # flutter_keyboard_visibility: 5.0.2
  android_intent: 2.0.2
  # maps_toolkit: 2.0.0
  # overlay_support: 1.2.1
  # flutter_calendar_carousel: 2.0.1
  intl: 0.17.0
  # pin_code_fields: 7.2.0
  video_thumbnail: 0.3.3
  # toast: 0.1.5
  preload_page_view: 0.1.6
  video_player: 2.1.6
  flutter_countdown_timer: 4.1.0
  video_compress: 3.0.0
  cupertino_icons: 1.0.3
  share: 2.0.4
  flutter_svg: 0.22.0
  hive: 2.0.4
  hive_flutter: 1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: 1.1.0
  build_runner: 2.0.5

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Thin.otf
          weight: 100
        - asset: assets/fonts/ProximaNova-Light.otf
          weight: 300
        - asset: assets/fonts/ProximaNova-Regular.otf
          weight: 400
        - asset: assets/fonts/ProximaNova-Medium.otf
          weight: 500
        - asset: assets/fonts/ProximaNova-Semibold.otf
          weight: 600
        - asset: assets/fonts/ProximaNova-Bold.otf
          weight: 700

  assets:
    # assets-generator-begin
    # assets/images/*
    - assets/images/app_logo.png
    - assets/images/arrow_down.png
    - assets/images/arrow_left.png
    - assets/images/arrow_right.png
    - assets/images/arrow_up.png
    - assets/images/back_arrow.png
    - assets/images/branch_marker.png
    - assets/images/brand_icon.png
    - assets/images/calender_icon.png
    - assets/images/call_icon.png
    - assets/images/camera_access.png
    - assets/images/camera_blue_icon.png
    - assets/images/camera_icon.png
    - assets/images/capture_icon.png
    - assets/images/check_in_icon.png
    - assets/images/check_out_icon.png
    - assets/images/close_icon.png
    - assets/images/comment_icon.png
    - assets/images/competition_icon.png
    - assets/images/cuppon_icon.png
    - assets/images/delete_icon.png
    - assets/images/error_artwork.png
    - assets/images/filter_icon.png
    - assets/images/gallery_access.png
    - assets/images/image_test.jpeg
    - assets/images/location.png
    - assets/images/location_access.png
    - assets/images/location_artwork.png
    - assets/images/location_in_range_icon.png
    - assets/images/logout_icon.png
    - assets/images/marker.png
    - assets/images/mic_access.png
    - assets/images/mic_black.png
    - assets/images/mic_blue_icon.png
    - assets/images/mic_gray.png
    - assets/images/mic_icon.png
    - assets/images/microphone.png
    - assets/images/next_arrow.png
    - assets/images/next_question_icon.png
    - assets/images/notification_icon.png
    - assets/images/notification_message_icon.png
    - assets/images/notification_task_icon.png
    - assets/images/pencil_artwork.png
    - assets/images/person_info.png
    - assets/images/pervious_question_icon.png
    - assets/images/play.png
    - assets/images/previous_arrow.png
    - assets/images/profile_icon.png
    - assets/images/promblem_icon.png
    - assets/images/promotion_icon.png
    - assets/images/remove_icon.png
    - assets/images/report_camera_icon.png
    - assets/images/report_icon.png
    - assets/images/report_mic_icon.png
    - assets/images/settings_icon.png
    - assets/images/test_background.png
    - assets/images/three_dots.png
    - assets/images/ticket_icon.png
    - assets/images/visits_icon.png
    # assets/animations/*
    - assets/animations/loading.flr
    # assets/svg/*
    - assets/svg/logo.svg
    # assets-generator-end
